

spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:ezfarmdb
      driver-class-name: org.h2.Driver
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true
server:
  port: 9090